<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Classify
 *
 * Classify Custom Image Recognition Service
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@inoven.ai
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createNewModel
     *
     * Create New Model.
     *
     */
    public function testCreateNewModel()
    {
    }

    /**
     * Test case for deleteModel
     *
     * Delete Model.
     *
     */
    public function testDeleteModel()
    {
    }

    /**
     * Test case for getModelsList
     *
     * Get Models List.
     *
     */
    public function testGetModelsList()
    {
    }

    /**
     * Test case for tagImageByUrl
     *
     * Tag Image by Using Image Url.
     *
     */
    public function testTagImageByUrl()
    {
    }

    /**
     * Test case for tagLocalImage
     *
     * Predict by Image.
     *
     */
    public function testTagLocalImage()
    {
    }

    /**
     * Test case for updateModel
     *
     * Update Model.
     *
     */
    public function testUpdateModel()
    {
    }
}
